
Neos:
  Neos:
    fusion:
      autoInclude:
        CodeQ.ContentReferences: true
    userInterface:
      translation:
        autoInclude:
          CodeQ.ContentReferences:
            - 'NodeTypes/*'
